
services:
  mysql_db:
    image: mysql:latest
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1111111"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    depends_on:
      - api
    build:
      ./frontend
    ports: 
      - "5173:5173"
    environment: 
      - PORT=5173
    volumes: 
      - ./frontend/src:/usr/src/app/src
  api:
    depends_on:
      mysql_db:
        condition: service_healthy
    build:
      ./backend
    ports: 
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes: 
      - ./backend/src:/usr/src/app/src
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
